# Generated by Django 5.2.4 on 2025-07-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('PENRO', 'Penro'), ('CENRO', 'Cenro'), ('Evaluator', 'Evaluator')], max_length=20)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_pic', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
